version: "3"

services:
  postgres:
    image: postgres:14
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    env_file:
      - .env.development

  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
    environment:
      - AWS_DEFAULT_REGION=ap-northeast-2
      - SERVICES=s3
      - EXTRA_CORS_ALLOWED_ORIGINS=*
